version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - ./docker/env/.env.django
      - ./docker/env/.env.dbcreds
    depends_on:
      - db
  tasks:
    build:
      context: .
      dockerfile: Dockerfile.task
    depends_on:
      - db
  db:
    image: mysql:8.0.22
    env_file:
      - ./docker/env/.env.db
      - ./docker/env/.env.dbcreds

