# GUNICORN / DJANGO: WEB APPLICATION

FROM python:3.8.3-alpine
WORKDIR /src
ENV PYTHONUNBUFFERED 1

# pip packages
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
COMMAND ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
