# Generated by Django 3.1.3 on 2020-12-01 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django_mysql.models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('needs_name_matching', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownZoomName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meeting_set_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zar.meetingsetmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawMeetingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('meeting_set_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='zar.meetingsetmodel')),
            ],
            options={
                'verbose_name_plural': 'Raw meeting data',
            },
        ),
        migrations.CreateModel(
            name='MeetingCompletedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('meeting_time', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meeting_set_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_reports', to='zar.meetingsetmodel')),
            ],
        ),
    ]
