# Generated by Django 3.1.3 on 2020-11-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0002_meetingsetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcompletedreport',
            name='meeting_set_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_reports', to='zar.meetingsetmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingsetmodel',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unknownzoomname',
            name='meeting_set_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unknown_names', to='zar.meetingsetmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unknownzoomname',
            name='real_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
