# Generated by Django 3.1.3 on 2020-11-24 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0004_rawmeetingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsetmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
