# Generated by Django 3.1.3 on 2020-11-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0005_meetingsetmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcompletedreport',
            name='owner',
        ),
        migrations.AlterField(
            model_name='rawmeetingdata',
            name='meeting_set_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='zar.meetingsetmodel'),
        ),
    ]
