# Generated by Django 3.1.3 on 2020-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0006_auto_20201124_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsetmodel',
            name='needs_name_matching',
            field=models.BooleanField(default=False),
        ),
    ]
