# Generated by Django 3.1.3 on 2020-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0007_meetingsetmodel_needs_name_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unknownzoomname',
            name='meeting_set_model',
        ),
        migrations.AlterField(
            model_name='meetingsetmodel',
            name='needs_name_matching',
            field=models.BooleanField(default=True),
        ),
    ]
