# Generated by Django 3.1.3 on 2020-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0008_auto_20201127_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownzoomname',
            name='zoom_name',
            field=models.CharField(max_length=50),
        ),
    ]
