# Generated by Django 3.1.3 on 2020-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0010_auto_20201129_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
