# Generated by Django 3.1.3 on 2020-11-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0011_report_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
    ]
