# Generated by Django 3.1.3 on 2020-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0012_remove_report_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmeetingdata',
            options={'verbose_name_plural': 'Raw meeting data'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
