# Generated by Django 3.1.3 on 2020-11-15 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_ea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
