# Generated by Django 3.1.3 on 2020-11-15 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_ea', '0002_emailconfirmationtoken_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
