# Generated by Django 3.1.3 on 2020-11-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_attendance_reporter', '0002_meetingcompletedreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingcompletedreport',
            old_name='datetime',
            new_name='meeting_time',
        ),
    ]
